config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :jobs
  get 'users/new' => 'users#new', as: :new_user
  post 'users' => 'users#create'
  get '/login'     => 'sessions#new'
	post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :job_tags
  has_many :tags, :through => :job_tags
  belongs_to :user
  validates :title, :description, presence: true
end

app/models/job_tag.rb
class JobTag < ApplicationRecord
  belongs_to :job
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :job_tags
  has_many :jobs, through: :job_tags
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :jobs
  validates :display_name, :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login][:email].downcase)
    
    if user && user.authenticate(params[:login][:password]) 
      session[:user_id] = user.id.to_s
      redirect_to jobs_path, notice: 'Successfully logged in!'
    else
      flash.now.alert = "Incorrect email or password, try again."
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    @user.email.downcase!
    
    if @user.save
      flash[:notice] = "Account created successfully!"
      session[:user_id] = @user.id.to_s
      redirect_to user_path(@user)
    else
      flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
      render :new
    end
  end

private

  def user_params
    params.require(:user).permit(:display_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="card">
  <h1>Welcome to the Rennielist</h1>
  <%= button_to 'Find Work', jobs_path, class: 'jobs-button' %>
  <%= button_to 'Find Help', new_job_path, class: 'jobs-button' %>
</div>

app/views/jobs/index.html.erb
<table class="jobs-table">
  <thead>
    <tr>
      <th>Job Title</th>
      <th>Posted By</th>
      <th>Posted On</th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do | job | %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.user.display_name %></td>
        <td><%= job.created_at.strftime('%m/%d/%Y') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rennieslist</title>
    <script src="https://kit.fontawesome.com/cb98ee1bc5.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Goudy+Bookletter+1911|Raleway&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    
    <% if notice %>
      <%= notice %>
    <% end %>
  
    <% if alert %>
      <%= alert %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <span class="navbar-toggle" id="js-navbar-toggle">
    <i class="fas fa-bars"></i>
  </span>
  <a href="#" class="logo">RL</a>
  <ul class="main-nav" id="js-menu">
    <li>
      <%= link_to 'Job Board', jobs_path, class: 'nav-links' %>
    </li>
    <% if current_user %>
      <li>
        <%= link_to 'View Profile', user_path(current_user), class: 'nav-links' %>
      </li>
      <li>
        <%= link_to 'Logout', logout_path, method: 'delete', class: 'nav-links' %>
      </li>
    <% else %>
      <li>
        <%= link_to 'Login', login_path, class: 'nav-links' %>
      </li>
      <li>
        <%= link_to 'Register', new_user_path, class: 'nav-links' %>
      </li>
    <% end %>
  </ul>
</nav>

<script>
let mainNav = document.getElementById('js-menu');
let navBarToggle = document.getElementById('js-navbar-toggle');
navBarToggle.addEventListener('click', function () {
  mainNav.classList.toggle('active');
});
</script>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :display_name %>
    <%= f.text_field :display_name, autofocus: true %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Sign up!" %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= current_user.display_name %>